apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      # Audit any write to /etc (so we can detect tampering)
      - path: /etc/**
        action: Audit
      # Block write to sensitive paths
      - path: /var/lib/postgresql/**
        action: Block
  process:
    matchPaths:
      # Block common tools that could be used for exfiltration
      - path: /usr/bin/curl
      - path: /usr/bin/wget
      - path: /usr/bin/nc
    action: Block
  network:
    matchProtocols:
      - tcp
    matchPorts:
      - port: 22
        action: Block
