apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default


spec:
  selector:
    matchLabels:
      app: wisecow

  severity: 5
  message: "Zero trust policy for wisecow"
  action: Audit

  process:
    matchPaths:
      - path: /usr/bin/curl
        action: Audit

  network:
    matchProtocols:
      - protocol: TCP
  file:
    matchPaths:
      - path: /etc/**
        action: Audit
      - path: /var/lib/postgresql/**
        action: Block

  process:
    matchPaths:
      - path: /usr/bin/curl
        action: Block
      - path: /usr/bin/wget
        action: Block
      - path: /usr/bin/nc
        action: Block

  network:
    matchProtocols:
      - protocol: TCP

  action: Block